export type ThoughtFeelingType = "사고" | "기분" | "상황";

export const THOUGHT_FEELING_ITEMS: { text: string; answer: ThoughtFeelingType }[] = [
  { text: "불안하다.", answer: "기분" },
  { text: "집에 있다.", answer: "상황" },
  { text: "나는 이 일을 할 수 없을 것이다.", answer: "사고" },
  { text: "슬프다.", answer: "기분" },
  { text: "친구와 전화를 하고 있다.", answer: "상황" },
  { text: "짜증이 난다.", answer: "기분" },
  { text: "차를 몰고 있다.", answer: "상황" },
  { text: "나는 항상 이런 방식으로 생각을 할 것이다.", answer: "사고" },
  { text: "직장에 있다.", answer: "상황" },
  { text: "나는 이성을 잃고 있다.", answer: "사고" },
  { text: "화가 난다.", answer: "기분" },
  { text: "나는 실력이 없다.", answer: "사고" },
  { text: "오후 4시.", answer: "상황" },
  { text: "끔찍한 일이 일어날 것 같다.", answer: "사고" },
  { text: "제대로 되는 일이 하나도 없다.", answer: "사고" },
  { text: "실망스럽다.", answer: "기분" },
  { text: "나는 이 일을 절대로 극복할 수 없을 것이다.", answer: "사고" },
  { text: "음식점에 앉아 있다.", answer: "상황" },
  { text: "나는 자제력을 잃었다.", answer: "사고" },
  { text: "나는 실패자다.", answer: "사고" },
  { text: "엄마와 전화를 하고 있다.", answer: "상황" },
  { text: "그녀는 사려 깊지 않다.", answer: "사고" },
  { text: "우울하다.", answer: "기분" },
  { text: "나는 패배자다.", answer: "사고" },
  { text: "죄책감이 든다.", answer: "기분" },
  { text: "아들 집에 있다.", answer: "상황" },
  { text: "심장마비가 일어날 것 같다.", answer: "사고" },
  { text: "나는 이용당했다.", answer: "사고" },
  { text: "잠을 이루려고 노력하면서 침대에 누워 있다.", answer: "상황" },
  { text: "이 일이 잘되지 않을 것이다.", answer: "사고" },
  { text: "부끄럽다.", answer: "기분" },
  { text: "나는 가진 것을 전부 잃게 될 것이다.", answer: "사고" },
  { text: "심한 공포를 느낀다.", answer: "기분" },
];
